config/routes.rb
Rails.application.routes.draw do
  # get 'animes/index'
  # get 'animes/new'
  # get 'animes/edit'
  # get 'animes/show'

  root to: 'application#welcome'

  get '/signup', to: 'users#new'#, as: signup
  post '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #login route 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  #logout route 
  post '/logout' => 'sessions#destroy'

  resources :animes #, only: [:show, :edit, :update, :destroy]

  #'/users/:id/animes'
  #'/users/:id/animes/new'
  resources :users do 
    resources :animes, only: [:index, :new, :create] #i only wanna do nested for index, CHANGE LATER?
  end 

  #nested routes should go in one direction PARENT => CHILD
  # we only want index, new, create 

  #'/genres/:id/animes'
  #'/genres/:id/animes/new'
  resources :genres do #PARENT
    resources :animes, only: [:index, :new, :create]  #CHILD. => will creaate 7 nested restful routes 
  end 

  #@anime.genre
  #callbacks to domain, applied on google side 

  get '/auth/:provider/callback', to: 'sessions#omniauth'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :animes
    has_many :users, through: :animes

    # accepts_nested_attributes_for :animes, :users
    validates :name, uniqueness: true, presence: true

    #scope method can be written 2 ways 
    #class method 

    def self.genres_animes 
        joins(:animes).group('genres.name')
    end 


    #scope method
    # scope :alpha, -> {joins(:animes).where('animes.name').group('genres.name')} 
    #{order('title')}
    # scope :alpha, -> {order('animes.title')}
    

    # scope :genres_animes, -> joins(:animes).group('genres.name')
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def index 
        # @genres = Genre.all
        @genres = Genre.genres_animes

    end 

    def new 
        @genre = Genre.new
        redirect_to new_anime_path
    end 

    def create 
        @genre = Genre.new(genre_params)
        if @genre.save 
            redirect_to genre_path(@genre)
        else
            render :new 
        end 
    end 

    def show 
        @genre = Genre.find_by_id(params[:id])
        
    end 

    # def edit 
    # end 

    # def update 
    #     if @genre.update(genre_params)
    #         redirect_to genre_path(@genre)
    #     else 
    #         render :edit 
    #     end 
    # end 

private 

    def genre_params
        params.require(:genre).permit(:name)
    end 
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/edit.html.erb
<h1> EDIT Genre </h1>

DO I WANT TO BE ABLE TO EDIT GENRE?? 

<%= form_for(@genre) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit%>

<% end %>

app/views/genres/index.html.erb
<h2> Pick A Genre </h2>

<%= link_to "Or Create One", new_genre_path %> <br><br>


<% @genres.each do |g| %>
    <%= link_to g.name, genre_animes_path(g)%>

    <ul class="center"><% g.animes.alpha.each do |anime| %>
    
    <li><%= anime.title %></li>
    <% end %>

    </ul>
    
<% end %>

app/views/genres/new.html.erb
<h1> Add a Genre </h1>


<%= form_with model: @genre do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit%>

<% end %>

app/views/genres/show.html.erb
<h1> Genre Show </h1>

<%= @genre.name %> 


<%# <%= @genre.users %> 

<% @genre.users.each do |g| %>
<%= g.username %>
<% end %>

<% @genre.animes.each do |a| %>
<%= a.title %>
<% end %>

<h3> Add An Anime in This Genre: </h3>

<%= link_to 'Add A New Anime', new_genre_anime_path(@genre) %>