config/routes.rb
Rails.application.routes.draw do
  # get 'animes/index'
  # get 'animes/new'
  # get 'animes/edit'
  # get 'animes/show'

  root to: 'application#welcome'

  get '/signup', to: 'users#new'#, as: signup
  post '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #login route 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  #logout route 
  post '/logout' => 'sessions#destroy'

  resources :animes #, only: [:show, :edit, :update, :destroy]

  #'/users/:id/animes'
  #'/users/:id/animes/new'
  resources :users do 
    resources :animes, only: [:index, :new, :create] #i only wanna do nested for index, CHANGE LATER?
  end 

  #nested routes should go in one direction PARENT => CHILD
  # we only want index, new, create 

  #'/genres/:id/animes'
  #'/genres/:id/animes/new'
  resources :genres do #PARENT
    resources :animes, only: [:index, :new, :create]  #CHILD. => will creaate 7 nested restful routes 
  end 

  #@anime.genre
  #callbacks to domain, applied on google side 

  get '/auth/:provider/callback', to: 'sessions#omniauth'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToonWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <center>

    <div>
    <br>
      <% if logged_in? %>
      <h1> ToonWeb </h1>
        <%= link_to "Add New Anime", new_anime_path %> |
        <%= link_to "All Animes", animes_path %> | 
        <%= link_to "All Genres", genres_path %> |
        <%= link_to "All Users", users_path %> | 
        <%#= link_to "My Anime List", user_animes_path(@current_user)%>
        <%= my_animes_link %>
        <h3> Hello <%= @current_user.username %>! </h3>

        <%= button_to "Log Out", logout_path %>
      <%# else %>
        <%#= button_to "Log In", login_path %><%#= button_to "Sign Up", signup_path(@user) %><br>
    <% end %>
        
      
    </div>


    <div>
      <% if flash[:message] %>
        <%= flash[:message] %>
      <% end %>
      <%= @error || @error1 || @error2 || @error3 %>
      
    
     <%# @current_user_error = "You are not allowed to make those previous changes. Here is where you can."%>
    </div>

    <%= yield %>
   </center>
  </body>
</html>